/**
 * ─────────────────────────────────────────────────────────────────────────
 *  REAL MARIO + FLUDD MODEL
 * ─────────────────────────────────────────────────────────────────────────
 *
 *  public/models/mario_fludd.glb is generated by scripts/build-model.py from
 *  the .obj/.dae rips already in public/models/. 135 KB, ~2,700 triangles.
 *
 *  Sunshine stores Mario's colors in the texture atlas, not in materials: one
 *  ripped material covers the blue bib, blue legs AND the red sleeves. So the
 *  build script classifies each triangle by the color it samples from the
 *  atlas, splits the geometry into one mesh per slot, and rewrites the atlas so
 *  tinted regions carry luminance only. Tint x luminance then gives the right
 *  hue with the original shading intact.
 *
 *  Face, eyes, mouth and bare forearms keep their original pixels and are
 *  deliberately absent from the matchers below.
 *
 *  Model space: feet at y=0, 2.14 units tall, facing +Z.
 */

export const MARIO_MODEL_URL: string | null = `${import.meta.env.BASE_URL}models/mario_fludd.glb`

/**
 * slot id -> patterns matched (case-insensitively) against each mesh's name
 * and its material's name. Mesh names equal slot ids, so these are exact.
 */
export const MATERIAL_MATCHERS: Record<string, string[]> = {
  mario_cap: ['mario_cap'],
  mario_shirt: ['mario_shirt'],
  mario_overalls: ['mario_overalls'],
  mario_gloves: ['mario_gloves'],
  mario_shoes: ['mario_shoes'],
  mario_sunglasses: ['mario_sunglasses'],
  mario_sunshine_shirt: ['mario_sunshine_shirt'],

  // FLUDD: watergun_item.dae keeps its UVs after all — build_fludd_parts.py
  // classifies every triangle by the texel it samples from the item atlas and
  // scripts/build-fludd.mjs splits the pack into these meshes. Mesh names equal
  // slot ids, so the matchers are exact.
  fludd_paint: ['fludd_paint'],           // the yellow shell
  fludd_metal: ['fludd_metal'],           // every chrome part, one mesh
  fludd_straps: ['fludd_straps'],         // brown harness + brown pack box
  // The water sphere (mesh1, no atlas map) plus the blue rubber neck ring
  // between the body segments — both driven by the "Water tank" slot.
  fludd_model_tank: ['fludd_model_tank', 'fludd_trim'],

  // Still tint nothing — no separable geometry for them:
  //   fludd_spray_nozzle / fludd_hover_nozzle  — gray metal, not cleanly
  //     separable from the rest of `fludd_metal` without fragile spatial cuts.
  //   fludd_rocket_nozzle / fludd_turbo_nozzle — that geometry is in other
  //     .dae files entirely and isn't built into the model.
  //   fludd_water / fludd_water_highlight — the sphere is one mesh; its color
  //     is driven by `fludd_model_tank`.
}

/**
 * Per-slot recolor profile for the shader patch in applySkin.ts.
 *
 * The atlas is Sunshine's *original*, untouched. `hue` is the stock hue of the
 * slot's fabric (0..1); a texel is recolored only when its hue is within
 * `hueTol` of that and its saturation is at least `satMin`. That leaves the
 * shine sprites (yellow), the cap's "M", white trim and every shadow alone.
 * Output brightness tracks the texel's own luminance, normalized by `refLum`
 * (the region's typical luminance) and nudged by `lumGain`.
 *
 * `mario_gloves` matches any texel (satMin negative, hueTol > 1) because the
 * glove texture is a flat near-white that should take the color wholesale.
 */
export interface SlotTint {
  hue: number
  hueTol: number
  satMin: number
  refLum: number
  lumGain: number
}

export const SLOT_TINT: Record<string, SlotTint> = {
  mario_cap:            { hue: 0.00, hueTol: 0.06, satMin: 0.16, refLum: 0.34, lumGain: 1.10 },
  mario_shirt:          { hue: 0.00, hueTol: 0.06, satMin: 0.16, refLum: 0.34, lumGain: 1.10 },
  mario_overalls:       { hue: 0.60, hueTol: 0.12, satMin: 0.12, refLum: 0.24, lumGain: 1.15 },
  mario_sunshine_shirt: { hue: 0.48, hueTol: 0.14, satMin: 0.10, refLum: 0.82, lumGain: 1.00 },
  mario_shoes:          { hue: 0.07, hueTol: 0.05, satMin: 0.18, refLum: 0.36, lumGain: 1.15 },
  mario_gloves:         { hue: 0.00, hueTol: 9.99, satMin: -1.0, refLum: 0.82, lumGain: 1.00 },

  // Each FLUDD mesh is already a single color region (the build script split
  // it that way), so — like mario_gloves — the profile matches every texel and
  // recolors the whole mesh by its own luminance. refLum is the region's mean
  // stock luminance from build_fludd_parts.py.
  fludd_paint:          { hue: 0.00, hueTol: 9.99, satMin: -1.0, refLum: 0.83, lumGain: 1.05 },
  fludd_metal:          { hue: 0.00, hueTol: 9.99, satMin: -1.0, refLum: 0.57, lumGain: 1.10 },
  fludd_straps:         { hue: 0.00, hueTol: 9.99, satMin: -1.0, refLum: 0.27, lumGain: 1.15 },
  // Drives the blue rubber neck (`fludd_trim`), which does carry the item
  // atlas. refLum is that ring's mean stock luminance from
  // build_fludd_parts.py. The water sphere shares this slot but has no map, so
  // it falls through to the plain material.color path and ignores this profile.
  fludd_model_tank:     { hue: 0.00, hueTol: 9.99, satMin: -1.0, refLum: 0.42, lumGain: 1.10 },
}
